import { Schema, model } from "mongoose";

const TagsModel = new Schema(
  {
    name: {
      type: String,
      required: true,
      unique: true,
      trim: true,
      lowercase: true,
      enum: [
        // emotion tags
        "happy",
        "sad",
        "angry",
        "scared",
        "confused",
        "disgusted",
        "surprised",
        "calm",
        "tired",
        "bored",
        "excited",
        "sleepy",
        "lonely",
        "hungry",
        "thirsty",
        "sick",
        "annoyed",
        "curious",
        "blessed",
        "loved",
        "indifferent",
        "horny",
        // activity tags
        "running",
        "walking",
        "cycling",
        "swimming",
        "sitting",
        "standing",
        "sleeping",
        "reading",
        "writing",
        "listening",
        "watching",
        "eating",
        "drinking",
        "working",
        "studying",
        "shopping",
        "cleaning",
        "cooking",
        // location tags
        "home",
        "office",
        "school",
        "work",
        "gym",
        "park",
        "restaurant",
        "cafe",
        "bar",
        "shop",
        "hospital",
        "bank",
        "hotel",
        "airport",
        "train",
        "bus",
        "taxi",
        "car",
        "bike",
        "truck",
        "humor",
        "dark humor",
        "light humor",
      ],
    },
  },
  { timestamps: true }
);

export default model("tags", TagsModel);
